"use strict";
const content=document.querySelector("#content"),projectsNode=document.querySelector("#projects");
const escapeHtml=value=>String(value??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.message||"Request failed");return value}
function card(title,value){return `<article class="card"><small>${escapeHtml(title)}</small><pre>${escapeHtml(value)}</pre></article>`}
async function loadProjects(){try{const {projects}=await api("/api/v1/projects");projectsNode.innerHTML=projects.map(project=>`<button data-slug="${escapeHtml(project.slug)}"><strong>${escapeHtml(project.display_name||project.slug)}</strong><br><small>${escapeHtml(project.repository)} · ${project.task_count} tasks</small></button>`).join("")||"<p>No projects registered.</p>";projectsNode.querySelectorAll("button").forEach(button=>button.onclick=()=>loadProject(projects.find(p=>p.slug===button.dataset.slug)))}catch(error){projectsNode.textContent=error.message}}
async function loadProject(project){content.innerHTML=`<h2>${escapeHtml(project.display_name||project.slug)}</h2><div class="cards">${card("Repository",project.repository)}${card("Storage capacity",JSON.stringify(project.storage,null,2))}${card("Deployment",JSON.stringify(project.deployment,null,2))}${card("Runtime lock",JSON.stringify(project.runtime,null,2))}${card("Managed process",JSON.stringify(project.process,null,2))}</div><h2>Tasks</h2><p>Loading…</p>`;try{const {tasks}=await api(`/api/v1/projects/${project.slug}/tasks`);content.lastElementChild.outerHTML=tasks.length?`<table><thead><tr><th>ID</th><th>Title</th><th>State</th><th>Updated</th></tr></thead><tbody>${tasks.map(task=>`<tr data-task="${task.id}"><td>${escapeHtml(task.identifier)}</td><td>${escapeHtml(task.title)}</td><td class="tag">${escapeHtml(task.state)}</td><td>${escapeHtml(task.updated_at)}</td></tr>`).join("")}</tbody></table>`:"<p>No local tasks.</p>";content.querySelectorAll("tr[data-task]").forEach(row=>row.onclick=()=>loadTask(project,row.dataset.task))}catch(error){content.lastElementChild.textContent=error.message}}
async function loadTask(project,id){try{const view=await api(`/api/v1/projects/${project.slug}/tasks/${id}`),task=view.task;content.innerHTML=`<button id="back">← ${escapeHtml(project.slug)}</button><h2>${escapeHtml(task.identifier)} · ${escapeHtml(task.title)}</h2><p>${escapeHtml(task.objective)}</p><div class="cards">${card("Lifecycle",task.state)}${card("Heads",`base ${task.base_sha}\ncurrent ${task.current_head}\npublished ${task.published_head}`)}${card("Storage reservation",JSON.stringify(view.storage,null,2))}${card("Publication",JSON.stringify(view.publication,null,2))}</div><h3>Workpad</h3><pre>${escapeHtml(view.workpad?.body||"No workpad")}</pre><h3>Role runs</h3><pre>${escapeHtml(JSON.stringify(view.role_runs,null,2))}</pre><h3>Findings / blockers</h3><pre>${escapeHtml(JSON.stringify({findings:view.findings,blockers:view.blockers},null,2))}</pre><h3>Timeline</h3><pre>${escapeHtml(JSON.stringify(view.events,null,2))}</pre>`;document.querySelector("#back").onclick=()=>loadProject(project)}catch(error){content.textContent=error.message}}
loadProjects();
