"use strict";
const content=document.querySelector("#content"),projectsNode=document.querySelector("#projects");
const escapeHtml=value=>String(value??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.message||"Request failed");return value}
function card(title,value){return `<article class="card"><small>${escapeHtml(title)}</small><pre>${escapeHtml(value)}</pre></article>`}
function shortSha(value){return value?String(value).slice(0,12):"—"}
function statusClass(status){return String(status||"").toLowerCase().replace(/[^a-z0-9_-]/g,"")}
function renderReceipt(receipt,view){
  const task=view.task, workspace=receipt.workspace||{}, git=receipt.git||{}, summary=receipt.change_summary||{}, diff=receipt.diff||{};
  const published=git.published_head;
  const publication=published?`Published head ${shortSha(published)}`:"LOCAL ONLY — NOT PUBLISHED TO GITHUB";
  const result=git.current_head?`${shortSha(git.base_sha)} → ${shortSha(git.current_head)}`:"No recorded task head";
  const workspaceMessage=workspace.exists?"":"<p class=\"receipt-empty\">Workspace not currently present. SQLite task evidence is preserved.</p>";
  const commits=receipt.commits||[];
  const files=summary.files||[];
  const roles=view.role_runs||[];
  return `<section class="receipt" aria-labelledby="receipt-title">
    <div class="receipt-heading"><div><span class="eyebrow">EXECUTION RECEIPT</span><h3 id="receipt-title">Execution receipts</h3></div><span class="publication ${published?"published":"local"}">${escapeHtml(publication)}</span></div>
    <div class="cards receipt-summary">
      ${card("State",task.state)}${card("Workspace",workspace.wsl_path)}${card("Local branch",git.branch)}${card("Result",result)}
    </div>
    <div class="workspace-tools"><button id="copy-workspace" data-path="${escapeHtml(workspace.wsl_path||"")}">Copy path</button>${workspaceMessage}</div>
    <h4>Commits</h4>
    ${commits.length?`<div class="receipt-table-wrap"><table><thead><tr><th>Commit</th><th>Subject</th><th>Author / committer</th><th>Dates</th></tr></thead><tbody>${commits.map(commit=>`<tr><td><code>${escapeHtml(shortSha(commit.sha))}</code></td><td>${escapeHtml(commit.subject)}</td><td>${escapeHtml(commit.author_name)} &lt;${escapeHtml(commit.author_email)}&gt;<br><small>committer: ${escapeHtml(commit.committer_name)} &lt;${escapeHtml(commit.committer_email)}&gt;</small></td><td><small>authored ${escapeHtml(commit.authored_at)}<br>committed ${escapeHtml(commit.committed_at)}</small></td></tr>`).join("")}</tbody></table></div>`:`<p class="receipt-empty">No committed task changes.</p>`}
    <h4>Files changed <small class="muted">${summary.files_changed==null?"unavailable":`${summary.files_changed} · +${summary.insertions||0} −${summary.deletions||0}`}</small></h4>
    ${files.length?`<div class="receipt-table-wrap"><table><thead><tr><th>Status</th><th>Path</th><th>Changes</th></tr></thead><tbody>${files.map(file=>`<tr><td><span class="tag ${statusClass(file.status)}">${escapeHtml(file.status)}</span></td><td><code>${escapeHtml(file.path)}</code></td><td>+${file.insertions==null?"?":escapeHtml(file.insertions)} −${file.deletions==null?"?":escapeHtml(file.deletions)}</td></tr>`).join("")}</tbody></table></div>`:`<p class="receipt-empty">${workspace.exists?"No committed task changes.":"Workspace not currently present."}</p>`}
    <h4>Diff</h4>
    <pre class="diff ${diff.truncated?"truncated":""}">${escapeHtml(diff.unified_patch||"No committed task changes.")}</pre>${diff.truncated?"<p class=\"muted\">Diff output was capped for safe browser delivery.</p>":""}
    <h4>Role history</h4>
    <div class="receipt-table-wrap"><table><thead><tr><th>Role</th><th>Status</th><th>Round</th><th>Head</th></tr></thead><tbody>${roles.map(run=>`<tr><td>${escapeHtml(run.role)}</td><td><span class="tag ${statusClass(run.status)}">${escapeHtml(run.status)}</span></td><td>${escapeHtml(run.round)}</td><td><code>${escapeHtml(shortSha(run.head_sha))}</code></td></tr>`).join("")||"<tr><td colspan=4>No role runs recorded.</td></tr>"}</tbody></table></div>
  </section>`;
}
async function loadProjects(){try{const {projects}=await api("/api/v1/projects");projectsNode.innerHTML=projects.map(project=>`<button data-slug="${escapeHtml(project.slug)}"><strong>${escapeHtml(project.display_name||project.slug)}</strong><br><small>${escapeHtml(project.repository)} · ${project.task_count} tasks</small></button>`).join("")||"<p>No projects registered.</p>";projectsNode.querySelectorAll("button").forEach(button=>button.onclick=()=>loadProject(projects.find(p=>p.slug===button.dataset.slug)))}catch(error){projectsNode.textContent=error.message}}
async function loadProject(project){content.innerHTML=`<h2>${escapeHtml(project.display_name||project.slug)}</h2><div class="cards">${card("Repository",project.repository)}${card("Storage capacity",JSON.stringify(project.storage,null,2))}${card("Deployment",JSON.stringify(project.deployment,null,2))}${card("Runtime lock",JSON.stringify(project.runtime,null,2))}${card("Managed process",JSON.stringify(project.process,null,2))}</div><h2>Tasks</h2><p>Loading…</p>`;try{const {tasks}=await api(`/api/v1/projects/${project.slug}/tasks`);content.lastElementChild.outerHTML=tasks.length?`<table><thead><tr><th>ID</th><th>Title</th><th>State</th><th>Updated</th></tr></thead><tbody>${tasks.map(task=>`<tr data-task="${task.id}"><td>${escapeHtml(task.identifier)}</td><td>${escapeHtml(task.title)}</td><td class="tag">${escapeHtml(task.state)}</td><td>${escapeHtml(task.updated_at)}</td></tr>`).join("")}</tbody></table>`:"<p>No local tasks.</p>";content.querySelectorAll("tr[data-task]").forEach(row=>row.onclick=()=>loadTask(project,row.dataset.task))}catch(error){content.lastElementChild.textContent=error.message}}
async function loadTask(project,id){try{const view=await api(`/api/v1/projects/${project.slug}/tasks/${id}`);let receipt;try{receipt=await api(`/api/v1/projects/${project.slug}/tasks/${id}/execution-receipt`)}catch(error){receipt={error:error.message}}const task=view.task;const receiptHtml=receipt.error?`<section class="receipt"><div class="receipt-heading"><div><span class="eyebrow">EXECUTION RECEIPT</span><h3>Evidence unavailable</h3></div></div><p>${escapeHtml(receipt.error)}</p></section>`:renderReceipt(receipt,view);content.innerHTML=`<button id="back">← ${escapeHtml(project.slug)}</button><h2>${escapeHtml(task.identifier)} · ${escapeHtml(task.title)}</h2><p>${escapeHtml(task.objective)}</p>${receiptHtml}<h3>Workpad</h3><pre>${escapeHtml(view.workpad?.body||"No workpad")}</pre><h3>Findings / blockers</h3><pre>${escapeHtml(JSON.stringify({findings:view.findings,blockers:view.blockers},null,2))}</pre><h3>Timeline</h3><pre>${escapeHtml(JSON.stringify(view.events,null,2))}</pre>`;document.querySelector("#back").onclick=()=>loadProject(project);const copy=document.querySelector("#copy-workspace");if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(copy.dataset.path);copy.textContent="Copied";setTimeout(()=>copy.textContent="Copy path",1200)}catch(error){copy.textContent="Copy unavailable"}}}catch(error){content.textContent=error.message}}
loadProjects();
