"use strict";
const content=document.querySelector("#content"),projectsNode=document.querySelector("#projects");
const escapeHtml=value=>String(value??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const response=await fetch(path,options);const value=await response.json();if(!response.ok)throw new Error(value.message||"Request failed");return value}
function card(title,value){return `<article class="card"><small>${escapeHtml(title)}</small><pre>${escapeHtml(value)}</pre></article>`}
function shortSha(value){return value?String(value).slice(0,12):"—"}
function statusClass(status){return String(status||"").toLowerCase().replace(/[^a-z0-9_-]/g,"")}
function renderReceipt(receipt,view){
  const task=view.task,workspace=receipt.workspace||{},git=receipt.git||{},summary=receipt.change_summary||{},diff=receipt.diff||{};
  const runs=(view.role_runs||[]).slice().sort((a,b)=>String(a.started_at||"").localeCompare(String(b.started_at||"")));
  const roleRows=runs.map(run=>`<tr><td>${escapeHtml(run.role)}</td><td><span class="tag ${statusClass(run.status)}">${escapeHtml(run.status)}</span></td><td>${escapeHtml(run.working_round_number)}</td><td><code>${escapeHtml(shortSha(run.head_sha))}</code></td><td>${escapeHtml(run.result_summary||"—")}</td></tr>`).join("")||"<tr><td colspan=5>No retained role execution evidence.</td></tr>";
  const files=summary.files||[],commits=receipt.commits||[];
  return `<section class="receipt"><div class="receipt-heading"><div><span class="eyebrow">EXECUTION EVIDENCE</span><h3>Host-observed execution</h3><small>${escapeHtml(receipt.source||"unavailable")}</small></div><span class="publication ${task.published_head?"published":"local"}">${escapeHtml(task.published_head?"PUBLISHED":"LOCAL ONLY")}</span></div>
    <div class="cards receipt-summary">${card("Task state",task.state)}${card("Workspace",workspace.wsl_path)}${card("Workspace HEAD",git.head)}${card("Accepted HEAD",task.current_head)}</div>
    <h4>Lifecycle projection</h4><pre>${escapeHtml(JSON.stringify({lifecycle:view.lifecycle,working_rounds:view.working_rounds,planning_attempts:view.planning_attempts},null,2))}</pre>
    <h4>Role executions</h4><div class="receipt-table-wrap"><table><thead><tr><th>Role</th><th>Status</th><th>Working round</th><th>HEAD</th><th>Summary</th></tr></thead><tbody>${roleRows}</tbody></table></div>
    <h4>Writer deltas</h4><pre>${escapeHtml(JSON.stringify(view.writer_deltas||[],null,2))}</pre>
    <h4>Commits</h4><pre>${escapeHtml(JSON.stringify(commits,null,2))}</pre>
    <h4>Changed paths</h4><pre>${escapeHtml(JSON.stringify(files,null,2))}</pre>
    <h4>Diff</h4><pre class="diff ${diff.truncated?"truncated":""}">${escapeHtml(diff.unified_patch||"Unavailable")}</pre></section>`;
}
async function loadProjects(){try{const {projects}=await api("/api/v1/projects");projectsNode.innerHTML=projects.map(project=>`<button data-slug="${escapeHtml(project.slug)}"><strong>${escapeHtml(project.display_name||project.slug)}</strong><br><small>${escapeHtml(project.repository)} · ${project.task_count} tasks</small></button>`).join("")||"<p>No projects registered.</p>";projectsNode.querySelectorAll("button").forEach(button=>button.onclick=()=>loadProject(projects.find(p=>p.slug===button.dataset.slug)))}catch(error){projectsNode.textContent=error.message}}
async function loadProject(project){content.innerHTML=`<h2>${escapeHtml(project.display_name||project.slug)}</h2><div class="cards">${card("Repository",project.repository)}${card("Storage capacity",JSON.stringify(project.storage,null,2))}${card("Deployment",JSON.stringify(project.deployment,null,2))}${card("Runtime lock",JSON.stringify(project.runtime,null,2))}${card("Managed process",JSON.stringify(project.process,null,2))}</div><h2>Tasks</h2><p>Loading…</p>`;try{const {tasks}=await api(`/api/v1/projects/${project.slug}/tasks`);content.lastElementChild.outerHTML=tasks.length?`<table><thead><tr><th>ID</th><th>Title</th><th>State</th><th>Updated</th></tr></thead><tbody>${tasks.map(task=>`<tr data-task="${task.id}"><td>${escapeHtml(task.identifier)}</td><td>${escapeHtml(task.title)}</td><td class="tag">${escapeHtml(task.state)}</td><td>${escapeHtml(task.updated_at)}</td></tr>`).join("")}</tbody></table>`:"<p>No local tasks.</p>";content.querySelectorAll("tr[data-task]").forEach(row=>row.onclick=()=>loadTask(project,row.dataset.task))}catch(error){content.lastElementChild.textContent=error.message}}
async function loadTask(project,id){try{const view=await api(`/api/v1/projects/${project.slug}/tasks/${id}`);let receipt;try{receipt=await api(`/api/v1/projects/${project.slug}/tasks/${id}/execution-receipt`)}catch(error){receipt={error:error.message}}const task=view.task;const receiptHtml=receipt.error?`<section class="receipt"><h3>Evidence unavailable</h3><p>${escapeHtml(receipt.error)}</p></section>`:renderReceipt(receipt,view);content.innerHTML=`<button id="back">← ${escapeHtml(project.slug)}</button><h2>${escapeHtml(task.identifier)} · ${escapeHtml(task.title)}</h2><p>${escapeHtml(task.objective)}</p>${receiptHtml}<h3>Findings / blockers</h3><pre>${escapeHtml(JSON.stringify({findings:view.findings,blockers:view.blockers},null,2))}</pre><h3>Timeline</h3><pre>${escapeHtml(JSON.stringify(view.events,null,2))}</pre>`;document.querySelector("#back").onclick=()=>loadProject(project)}catch(error){content.textContent=error.message}}
loadProjects();
